aws_secret_key=
aws_access_key=
aws_region=
env_name =
vpc_cidr_block=
key_name=
instance_type=
aws_ami_capp=
aws_ami_eapp=
aws_ami_prometheous2=
aws_ami_prometheous1=
aws_ami_docs=
aws_ami_pgbouncer=
aws_ami_redis=
aws_ami_qa_build=
aws_ami_bastion=
aws_ami_worker=
aws_ami_nginx=
